/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2024.1.2406150513_p
    Soft IP Version: 1.2.0
    2024 08 24 00:06:07
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module qspi0 (a_clk_i, a_reset_n_i, int_o, qspi_io0, qspi_io1, qspi_io2,
    qspi_io3, sclk_o, ss_n_o, axi_awid_i, axi_awaddr_i, axi_awlen_i,
    axi_awsize_i, axi_awburst_i, axi_awlock_i, axi_awcache_i, axi_awprot_i,
    axi_awvalid_i, axi_awready_o, axi_wdata_i, axi_wstrb_i, axi_wlast_i,
    axi_wvalid_i, axi_wready_o, axi_bid_o, axi_bresp_o, axi_bvalid_o,
    axi_bready_i, axi_arid_i, axi_araddr_i, axi_arlen_i, axi_arsize_i,
    axi_arburst_i, axi_arlock_i, axi_arcache_i, axi_arprot_i, axi_arvalid_i,
    axi_arready_o, axi_rid_o, axi_rdata_o, axi_rresp_o, axi_rlast_o,
    axi_rvalid_o, axi_rready_i)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  a_clk_i;
    input  a_reset_n_i;
    output  int_o;
    inout  qspi_io0;
    inout  qspi_io1;
    inout  qspi_io2;
    inout  qspi_io3;
    output  sclk_o;
    output  [0:0]  ss_n_o;
    input  [3:0]  axi_awid_i;
    input  [31:0]  axi_awaddr_i;
    input  [7:0]  axi_awlen_i;
    input  [2:0]  axi_awsize_i;
    input  [1:0]  axi_awburst_i;
    input  [0:0]  axi_awlock_i;
    input  [3:0]  axi_awcache_i;
    input  [2:0]  axi_awprot_i;
    input  axi_awvalid_i;
    output  axi_awready_o;
    input  [31:0]  axi_wdata_i;
    input  [3:0]  axi_wstrb_i;
    input  axi_wlast_i;
    input  axi_wvalid_i;
    output  axi_wready_o;
    output  [3:0]  axi_bid_o;
    output  [1:0]  axi_bresp_o;
    output  axi_bvalid_o;
    input  axi_bready_i;
    input  [3:0]  axi_arid_i;
    input  [31:0]  axi_araddr_i;
    input  [7:0]  axi_arlen_i;
    input  [2:0]  axi_arsize_i;
    input  [1:0]  axi_arburst_i;
    input  [0:0]  axi_arlock_i;
    input  [3:0]  axi_arcache_i;
    input  [2:0]  axi_arprot_i;
    input  axi_arvalid_i;
    output  axi_arready_o;
    output  [3:0]  axi_rid_o;
    output  [31:0]  axi_rdata_o;
    output  [1:0]  axi_rresp_o;
    output  axi_rlast_o;
    output  axi_rvalid_o;
    input  axi_rready_i;
endmodule