/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2024.1.2406150513_p
    Soft IP Version: 1.0.0
    2024 08 24 00:01:17
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module mbconfig0 (pclk_i, rstn_i, apb_penable_i, apb_psel_i, apb_pwrite_i,
    apb_paddr_i, apb_pwdata_i, apb_pready_o, apb_pslverr_o, apb_prdata_o,
    config_active)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  pclk_i;
    input  rstn_i;
    input  apb_penable_i;
    input  apb_psel_i;
    input  apb_pwrite_i;
    input  [31:0]  apb_paddr_i;
    input  [31:0]  apb_pwdata_i;
    output  apb_pready_o;
    output  apb_pslverr_o;
    output  [31:0]  apb_prdata_o;
    output  config_active;
endmodule