/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2024.1.2406150513_p
    Soft IP Version: 2.5.0
    2024 08 24 02:52:22
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module pll0 (rstn_i, clki_i, lock_o, clkop_o, clkos_o, clkos2_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  rstn_i;
    input  clki_i;
    output  lock_o;
    output  clkop_o;
    output  clkos_o;
    output  clkos2_o;
endmodule