/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2024.1.2406150513_p
    Soft IP Version: 3.0.0
    2024 08 23 23:55:37
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module rst_sync0 (clk, pb_in_n, pb_out)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  clk;
    input  pb_in_n;
    output  pb_out;
endmodule