
/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2024.1.2406150513_p
    Soft IP Version: 3.0.0
    2024 08 23 23:55:37
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
(* ORIG_MODULE_NAME="rst_sync0", LATTICE_IP_GENERATED="1" *) module rst_sync0 (clk, 
        pb_in_n, 
        pb_out) ;
    input clk ; 
    input pb_in_n ; 
    output pb_out ; 
    parameter SIM = 0 ; 
    rst_sync0_ipgen_rst_sync #(.SIM(SIM)) rst_sync_inst (.clk(clk), 
                .pb_in_n(pb_in_n), 
                .pb_out(pb_out)) ; 
endmodule



`pragma protect begin_protected

`pragma protect version=1
`pragma protect author="Lattice Semiconductor Corporation"
`pragma protect author_info="Lattice Semiconductor Corporation"
`pragma protect encrypt_agent="Radiant encrypt_hdl"
`pragma protect encrypt_agent_info="Radiant encrypt_hdl Version 1.0"

`pragma protect encoding=(enctype="base64", line_length=64, bytes=256)
`pragma protect key_keyowner="Lattice Semiconductor"
`pragma protect key_keyname="LSCC_RADIANT_2"
`pragma protect key_method="rsa"
`pragma protect key_block
H0utz9zvwkvL/nYNaQCkvnqr/gL2whLXjp2GfyvwNAyZUP13cauA+k6mgslbLuex
K3chxZ7ZqdOKMreJtWI8FNXVQ+XxZn+zFZXJ4YDnHqn+NnDaCsH3tCbZ1JNG9H+Z
v9r2dnSKLFyBEP1dlLz9bWUCt0aWWlIfhw30WmhSa2FCmn30SK3U371TGUe0qUp5
5k2UtMmXNdO0+aLW1pFzIPu0TQGzqSPZHLmg1TFQURNfWnomYRcA2jfBvb4+7Arn
iEiEOXXivphxfQfO/Enul7VjSDU/5Pc4IlRsW/6c/VvddnIBNXltBM3+dKBXwi9A
OfaU6lV5thNT42DOuAdPow==

`pragma protect encoding=(enctype="base64", line_length=64, bytes=256)
`pragma protect key_keyowner="Synplicity"
`pragma protect key_keyname="SYNP15_1"
`pragma protect key_method="rsa"
`pragma protect key_block
R6kV3AjfnokJ3y+4L5hwAd34RXZ6lIHrE2F7uAfrVE7MTQi8ZFuyGBvZnEWIJf6O
J7I3J1wZNiQk/ozN/ouUsvf/67lWK8Qi3CCpRyDrIAJbz4xWRx6UM5GUS0qU0XsN
Ru1maHwcALiSiyRtrolQ1Z2yh/Yfm5+08CGKvFvp7ReJGtZl4+xtdE/GrPskAE2x
nxDObRkCBcsk3jO5B7JaVy/akSftl3DKSPUiaBr1apLsL46LScNK+AvyY15P9IxY
dLbyucWxJpmIBo/Cv2eadTT1M8xSKJx3T4rufAzMKoazykheAsLnFdEMPKjUph72
8qH2LBREqEhCkvNO94naQA==

`pragma protect encoding=(enctype="base64", line_length=64, bytes=256)
`pragma protect key_keyowner="Synplicity"
`pragma protect key_keyname="SYNP05_001"
`pragma protect key_method="rsa"
`pragma protect key_block
VzJjsLKJ1CaAZ9PKlHwR+eBHZivK55kx0PjoHdAjjGhR5ohZqCV/Lgtsf1kLkhY8
PGMYEkvg/6zJJ05gPoFSm65cg4xfmChyrMhfUDbs/YWy33dtXSnLmOa3VfZADQ+Q
p1TIZ9+15a4q+3SerXn7CSza2KBRbNbi/wLZu8N/+S7oHlA9SRP7fFQl2AytMw/t
1WTn1ZzLwMhN2b0qlO+vw/AaNVDl/5jia4Vh2IXId+QJ6/zkLq0PbVwv+D2ws0h0
gROCdSZ1EQXClPajRtoPA1dzEU/MYiineWCWP1ooQbtImgEbGUJffSUxX3Y4wUkK
7Mp2KS2zzU5mrX0hZ4eTZw==

`pragma protect encoding=(enctype="base64", line_length=64, bytes=256)
`pragma protect key_keyowner="Mentor Graphics Corporation"
`pragma protect key_keyname="MGC-VERIF-SIM-RSA-2"
`pragma protect key_method="rsa"
`pragma protect key_block
BEekAoqAE5TPS7sRtp6Z02rbbHBshzapxmeRtO7oOeX9Js+6G+Sbk78IFZZiOpph
MTovbZoMDSLcz2FxM+BXKsjQ/sH56Z/cu1L6G0TImN1ENl4rl/6UfPooPF512Zaz
Iq3qos28sAwi5LvDviAbtAhnb7hQSDIbPIyIXfMX669BymTvNUqvpSGjF84TT5Cl
jLLH9IwSeLsnGN0XNcg4J4uvilK/T2AMe+J4iZUfaC9mFbKfgTUrTgRqDQPe8JTm
UB0pM4zdC/jaWkiIIURsHp6drZHS8NiYSiQix07ObQMBImyoNfO8pzZUamcfiqys
zcZNdkSNyjDN4olwHOOtDA==

`pragma protect encoding=(enctype="base64", line_length=64, bytes=128)
`pragma protect key_keyowner="Synopsys"
`pragma protect key_keyname="SNPS-VCS-RSA-1"
`pragma protect key_method="rsa"
`pragma protect key_block
lbQ890hoKNB9d2BIERPtfELKZ8jWFdlHHaA2YB6L7x+AbnBvZowQRM3h7nSkCgVH
Nl3PZuybustD6GlyB9q7jav5OcaIZw33VYeQ4+X0CBoNv8tu167s3snC80MCjSUY
2XAIKg4wigxTU50gRKhM90CBmY/2uxG1JmYiPIeuAkw=

`pragma protect encoding=(enctype="base64", line_length=64, bytes=256)
`pragma protect key_keyowner="Aldec"
`pragma protect key_keyname="ALDEC15_001"
`pragma protect key_method="rsa"
`pragma protect key_block
ymyypynBr7fElMqyMVDjK+/EG0iRZiT3KzEzQgWCq7k9Q6bYf1Vi7BRzRgBW7FMp
WKCf3xJythE8DEgWYPTa+Pu3Qt8BEL/aaehCTki5xRvvAPPTJptLl3filxjGYJEW
hNoJBHibjWoAGzGlkXT+ITHUJKrz+LfHX5CLZ7K2lERB6L99vvOzj6orTMdiDYLP
BCCFK39gcABY0njfZ5V9VT/yrMs2Mr5DPFTcgdocoI0vjMj9RRpZAl/sQux8taiF
K3UMf1BYs0ojesDK5tWTCGJBRL5kNWp2y/Fud4KSw3YK9r2e3UJD4zE6qT/zi+xV
SVSI1riD0B6Hq9YEKPAjTA==

`pragma protect encoding=(enctype="base64", line_length=64, bytes=256)
`pragma protect key_keyowner="Cadence Design Systems."
`pragma protect key_keyname="CDS_RSA_KEY_VER_1"
`pragma protect key_method="rsa"
`pragma protect key_block
hjSjb50s37/a8CrKOs4JQa57o5P4mMkdRBQKLuCobtJtqQ7yAplWP3KN8UnOxCX/
hTBdS5j5w/qttgZXShkL7xcMcMlengdiLoOvtnrVRDn0W8JPChNNnN/Y/9KPS7Wt
ljxRb8xtY0JO1QDl+q9az5HkTV7YSAzWvDiyH2bAMUclSpx3Vv8glQgLZPp9wir2
+NVrhOfFCzr24cYCfENp6yYM7SoDKaYyLKeiQV8bhQnTcJfBl/qmuusROClF6jJW
5sDcL18GNnYqOr+1vA8FIPIemgrKBhRAQn4VrovnZuI3URiKhhpDzZ6zFAb+j+/Q
eMQAzA0BQbx82aa4CGr4+Q==

`pragma protect encoding=(enctype="base64", line_length=64, bytes=384)
`pragma protect key_keyowner="Lattice Semiconductor"
`pragma protect key_keyname="LSCC_RADIANT_3"
`pragma protect key_method="rsa"
`pragma protect key_block
dlop69VP6nNOF5gjWAcazH0KgyJZ8Asyb1UQBt24qW9iA052VCcQHMqgeInC0LAm
uilhKQrT4A3WDjx5VepHeVnZK93RbjxFwaC2IYfrO0ptByFrCliBWbTof4XYaVv/
lYmJD9oxi0x8msvV4YQ6PVoJoTTO6LFplVTZ28+8fwGWJdihc4TsWiSvbMucdwXx
fix7308ZsD5VObGvsJxabam9yUzrcblajMOUL7u3gl5x8nb6s95Hhj7+gaM0eEey
HLJ2A7qpkD5XR9eboWa/kVJlCI8dQ8S7CVlyXqmUXag1Js/FuKpiUsoqp20XSzXA
mazd388FnHqdw25s1xFW9+DouiKz3OzhNL4v0G3J/KDCydLnalr58B2eFcFUcN8+
Sq+ZXcS1A89eXzg+Q8gA+zHb67s8aqPiv5yzUfk6YXABMoKKv87S+sAbMDYvmqyl
HJYbrSb2wqJRP19G03CF9SKbBBQOlbBYHtHgjwqA+OjLsu+lfYwqZsyv72zeuC+C

`pragma protect data_method="aes256-cbc"
`pragma protect encoding=(enctype="base64", line_length=64, bytes=4128)
`pragma protect data_block
yYe5163eA1RWoO1f9JvFgOg6vfkZtDMyQZuTeJ8aiKGAb+egDx+wGIxi33yPMeCY
f65rtuI/JuVEEYJkCYDB/qp8/w+P3sX+ILV8eEuauqVmR2HrLqvo3NqWfkrlrFrR
QKr5s1c47TjStyGwuZbTYA1H3g2NsdtY79sZ+mOEMsAk6HcmiEYUk3+nsvaXQ13h
KpIWn7UoN/zScqyR+nchaGxvxZo7X4VlA+DFpqKydycgOkTFEgNfSe02WoTQRtM3
a5sqRf/MCaHvYOE+k+qjrizlW4AG+KH9OiZ7dIYGTp81ptH25WNwdhQYlC8qVsPD
wT9ghJLeOwCT6x2B3nx3X/TjOrR6ol78GnbOvF26ixA0OSLta4gjSqPH5WBeepOI
kF7GLRg/rtYpPLfcSSGLHGQNB5eVA0ENemIFdl4g55bHVlDbNTOP96BaJMLgLNCl
lEvg5ZPR6ua9lnQvI6FGga1/oAbP+d5cEVA/RnIYydiJppRcAu/hfl3sQ+Jr4iBN
YfuKGBXRUqaI6voMQmZ+xw53c3wd0wa19irWNFLh+WC0rlCjpG+528IXk3x1P+uZ
Nla58xCscf6jrtRcBRKUNjGGYN8mTa2o2xzPEwQtwKgD35HdgA5NLbkxL0W3LQfa
C5HHJWZhNZbd0sJH19NQmUocVMpTgChoQmh3AUWH9ohgkTtWQnCmmWZXyLS+5GNz
37zR4c4iiI4F9Gv6WJnfXvUksm0DCwutJ/M18JCWb8wWt41rqyvf/Iohg5DmLX8I
I+VGfbUV5/n9uY6T9WCNcmbMsc8wA7u5N4RQtjroeT6xMwOWeuHViIyQCKptu/0e
TjdBAwpoaev/R1iCpK8+OceUKUqma/7lXJRxIrWw8CycT+qHyl5RpMFFVlHCxjqC
cU6XX4zZZhVmaYTz/qzelLSPwTk+NkTGvAX1pdubbXBNVzTbMWU+bXJtE6pR2h3Y
7L+O8tj470iXPlBkIpmqB92nskJGzMpleXjm7npItUbQk+f4s/92Zz9X3eDIxXrF
Mt79nbeowxqNsdNaLcHziB3oazvDXZ2n/fCCN29TpGboVCAIru3Z9/Mt4BnSm/3k
0AnHmaNtPZplhvMzIdaHqCXVirBqin+ta2Nz6oms3+TETlqUvWvnT8wLC9caMpNs
Gfp8iBbzJKn8Gc6oy4IFbwTZNEZFOO774DYgjk20dTHNam3LVdJmV3sqAxSJ0qe5
19FqmTWVYWfZbSDSgosUsnCeqi8olfShY/tgbWZStFsdaX9U/mBTsZSJAxX2tFau
20XTaOhRYxIr+35D3iwICDLrlc36066lyYjf0JTBmclNv0Ovp/7h2lXvs1pnxW2t
s0t0fZxLDTaW6Tmv9I/VUhIBvzsdNknoMTYkG+1ONIViPsBCap2qfm0TH9sGSNTo
sHYpmj5IB6TWgnKLtIRBc88/svr8yhP90nfDVW0MDavspDoeh+KtGQizcwkFlwVr
SbPyp+ZVyRhtXe/LdQFLzoz424xMBJzs7SPX0gNGgpjF5tdQyPiv2eOqYtAZ4cPI
NVlpVLEUproixFsvo48HNOafZQjItjPSMUFxHJdoLSaBpKY8+2BpV/ReZJegVLZp
OsfiMUUqyAlHJsNztl4w4V7Kt6j/X5faotRXJY7OVFvhMcIDELa09ov5pZkA0qpS
IH98zD6RkDLRxHtBu3BCdmO6fVuLaj5t1SlNI+Jt/S/PrhmbV0sLO3np8oX77RYT
zwpzdcMqMkWNwl6X+0j84XAQOUsxRs+UCmvUFWAzuRwnjTNOIJwKqoyKkF8fh6x9
rjAaq6v3tmu74yMkSBJgR4NH9Bk0vhVVCzJlcsHPvbiRLSRK5iTTxGq5wdveO6cF
34rpewBJqgcFaRrtqfQuWMyqFZinugPT0rvPPJVOkjClORDDp097rltobxtM1057
dpvC6KRRscdxFAhpC24Wnk0XzkpNJNeZs2ZsCbYZD0JroZTxRLDEImDOcmzCGvgt
6mRMuB9twVWirXWzhxTip+/MAd1eZojI8lT5U+HeFEd2gJyq+jU+JmPfJaPaXJfP
7hKCGH4XcL/yA5tQPpgwG0gEQynGmMmRL+QzRpv4fq1AGdJKWUDi5TZeIuQrKqpO
ul1rTCi3aMnPCZHQ6Dabvo6cxuYhGoSrNZ1H7O/f0bteorq7gvMQOLlWW8o8S/hj
8ghPaZBko9EnpGKHxkbODNi8spvT3XIh5301GvclX+53ds5JJwY5KuRIsqHOpbsE
fzc1zywHWtj5UtcjjWLuqHhygw6/N0ykQSJ5f4C0yfAGO6z/Mu6O3k5H6pjBwEYD
NFBhA7s9vCkGLq1qvldT9Cbll1fPptOcN2bVp9OPGNmn2Xb5YYfOpbkfGC2/NgQo
qpSI/vsO8tCJIkPyrNpwWLNbXcb0QOv3Bjj1EFgGUBhRp1jdlgv2h16QDe4XJKlB
f5y27ixqxe5OSxEJ1GP9PB8FXzRMT5n/xF9GKmCxH3PHKN7cLiYLiFHVzURU6ZsQ
MB/sX6xjzjcIw2yYXayZtpZxUpUwAiT+nbO+4ZMubXH/iI34jI6HjOV+sA/34Pkb
islALWODwsId+FvK7+NG/qLMMghsJZela/uJZa/ulJaG1d0tODcTV0VNjEFV4rju
Se3ZlmkvQSNui+X/eyboHXlqgCl2Sh+45kfVIE6kZ3cPN3AI3oyybyQZqDILmwkx
7S9cV+dc8HddRFebMQxFZTzzJi6FlTFJbC2nmjX0UYT+Kx0Hsm1S+TllrDpHh/7C
bfgHDUWMKHX5t0S5soeKYjs08HO8VFkBDi35QNI+ZxzQPwYdmrH/Cq7BW56VM4Sn
UMQFiaSCqA5TSzX5ULgU+XD9HyHmqsTvlIZNwZTvdOX7SamMfUSHAB6pNcPJSliE
wYUmGwzGS/bB/wlD8rhsdKS2o+6VwbjxB4gzTb7gaKfW6zDiDd9NS5kQXR5kJhde
ZhiiV5rmtsC8qlwROIcnxSUdoYC6Tr4sZAYa2vemWqY0pqdL5t8yNJjBrkhsMsf6
/vZiFiRip4SUPtZtR4xwuupeROeIWnGHhXeyMY4H2DvtOGzwBFgZT5jyIsaiUw+L
BwIP2aJ/WAT5l2TNEyrMr1n+Ui0MZLGtnsz8rTa7/EJawSBh08LagrwUDG2dcdM7
l/vS38icQW47MHPkCdOFmHjgbx+k9MkSh9CLamwCOfnWMoi0dxX7NU4rGPM1YL88
KfkQo8StiV5yJ2PLez0j0LwQe9o+PWbSjH6y6QLRu3RQPV9+LmYaeqlz9bC4/tqq
lfooYNnPMJmd485Kly8ZzWGD6xYO1ctwqRWuYIVgPJcly0XpIzziwoZCMzeNgQuT
8ozsaHfS7Hv0AFYdU3vSW8STM7vHsQTmk8qCmIkLMPYYywt4JLf8WOqhPAS0sTC1
CJA8buURh1vjuHsDk4gGPQq0p43KdJYnRjZgCoalfUqlYVgtH2ujj64FKHPnxVEg
Aiu1TejrFNZWkYmkl9T+/K1TBYbqpTvCoSpdUDOJYKzJVqAuP/MiWvxq+vQObVt8
0zchleEKau/Y6fSxGK3RgFp4aD/wtwLA5Hl+lcfVLSryGapySEugLx2QZECHZkh2
MvVQqoyAflNT6iJAI+yNtzY6NsOwHwBKvyWCwaUgdWAvJTPMGS8PDpn6+xRCqNVk
YTvCfbT28Dh8iXUEKv6r+R4eu32SOa2w46Y6W6HrCxFu0WIdtNUZwLGJz5pBY5/m
bYHtQlHS9K061F9CmS/v33X2Fy37mW8+nLhk/swsmZ1FR19fIvtC7uFdWPQAxC4t
xxbtL2im/ZD1fHXmXLLi9NAbetcpGnv2CJPNHH2MbmwqPOREvZKAtVBm7eiUnYzt
Qz7bV8tTc3xgZwsAH06eFUCHeTxZvQGC6ZXukfaacLzs/RwqRv8Zf6QjZc52IXYd
vvDoOew69M6xRevsfSCD8tU9CDJWeTOlDAb1TVSjMXRZw7/i4n3baHQysgYqkoDm
Mx+aHuB+9jZE6QMIfG/EWE1Ru4lVfqvULHpMs/pMz6IU4lf22+Ko6ZW3fp0RAt9M
QKdUOGk/ic5TpoXYDYcEi2bGxyVaNgwWqZE7EPJQDpXc1ZvjGoQovY0vbx1JpQDS
gcYI8oOLEow8G29xwKTGTZtGiQ+bqIpx7j4sksKArioJ+xIT5nP8Y73yAeIVa1SC
eJnqnYuTqY3nGf/YpQp/wP1hI5LUBwWPpX6hislxKxUF9xEAvRUExiQi78Omn2zQ
vNZsj8KTy+aXsjW25DdyKTIQL1DC49MrVVDsPF3hS9TVDBsGVI84f7CBJ7zm3HGw
/LFdaC1SMWB55Kf11N05x71PTQbzAAoo+iwpssl2fl9YV3uYZDmn5MSzmGEkj+h+
yFqwYSK17QtyoP719TQXfMBLN2/ME1MQl8gRPVSO7Btdt/qVzkbFk5gVoQq+GJDb
e6nqCCgTPWh118cMoe6vOsszZAt7aa3j0X31vJaaW5HxgsELwHrqL7NTIF03GpTV
PY25bp9/cBoznH5mkMw1mCWjsEpYIWb1k08f/nfKa4TC6Qck+x69O2lWLNID08pk
UQUXyg4xP9Cjp5bD2IUfXBeWI+z0zw3KxRbkVUJ+MRZpJ2uNHduTBjh47KQ+KIFP
1yOs1rJvqE/U5ms3kmWU5tz04j4cCq0391Ddm07JkrJTAZl39vDFX7VuBJga61kO
Ut5Tj5m/wiuSAHF2fupNtVYwg6AJ+1j8jRVHASXN4TU8BknFi6hWG9QBh7j0XS4N
rihypytYsz09su0GgqsNkpf3y+D+XBYsJs2sQALsKzMNpDkHHzpd2PWiV/dwoeDo
BVun3CDqWWeSqlitf1D1Z973JUOPdEayqkkrOTi4FCSHf2RwRFOMb9/mgXCBzlLt
cfIgdBVAYUvqCTBiTuR767DX37p2kvMKUtGlMlks1/a5D4zqc6EuiFZy6xlijcHM
ibVnW8yzKy0GVdMA+A5yvI3KDALZCKQYVjE49itNhEZXPb+uucIFJUkgIOLrBpTA
Xy2VDDuDoDGsqhQ4FvzASZXpJn1Kf+np5cCSL5jAuORRnLiXo5ro+8NtUKXrTGSZ
iITVccRXvxcGi3kWVBuAMrHwnKg2K50vLxyNfraYooHOJMgZPNW/+7zAVxlSTthD
q9cIWB9mJaNGtvMWBNTS74puhXBbf9fLPQ9IUP0Rzb2RcjkAiCUwJKgeGfHjsOqb
E/YDsavLaLjZQn75YWDGQGbod5fT+3tNq0gD0EkdP3QARtuWnk6E0L1Z9OetfzSk
1EEJzsi340vsV9TvlN+hqzUA9NrbRXZdzy/dxKAvgdn2kwoI/l6e3qYdtgbWB1Pm
6es0e98ZXxyJt+dNdesTSyL48r7kgrUTqKMtDACLKPNH3KZLTuvnMuZqb3byrC8g
ilvNoMIHHfgw48O5HMD/xDdqDLbwiJaskLDc1jgZuRLG3EmfAg/Fu58DWleznp+m
KQk1VVClTR+lD31v+DXjT4NTOcncAYBg/0R2VtDfTOt5AIsDntg+ZZxeGNpxpIwS

`pragma protect end_protected

