--  >>>>>>>>>>>>>>>>>>>>>>> COPYRIGHT NOTICE <<<<<<<<<<<<<<<<<<<<<<<<<
--	  ------------------------------------------------------------------
--	  Copyright(c) 2019 - 2024 by Lattice Semiconductor Corporation
--      ALL RIGHTS RESERVED
--	  ------------------------------------------------------------------

--	  IMPORTANT: THIS FILE IS USED BY OR GENERATED BY the LATTICE PROPEL™
--DEVELOPMENT SUITE, WHICH INCLUDES PROPEL BUILDER AND PROPEL SDK.

--	   Lattice grants permission to use this code pursuant to the
--       terms of the Lattice Propel License Agreement.

--     DISCLAIMER :

--       LATTICE MAKES NO WARRANTIES ON THIS FILE OR ITS CONTENTS, WHETHER
--EXPRESSED, IMPLIED, STATUTORY, OR IN ANY PROVISION OF THE LATTICE PROPEL
--LICENSE AGREEMENT OR COMMUNICATION WITH LICENSEE, AND LATTICE SPECIFICALLY
--DISCLAIMS ANY IMPLIED WARRANTY OF MERCHANTABILITY OR FITNESS FOR A
--PARTICULAR PURPOSE.LATTICE DOES NOT WARRANT THAT THE FUNCTIONS CONTAINED
--HEREIN WILL MEET LICENSEE'S REQUIREMENTS, OR THAT LICENSEE'S OPERATION OF
--ANY DEVICE, SOFTWARE OR SYSTEM USING THIS FILE OR ITS CONTENTS WILL BE
--UNINTERRUPTED OR ERROR FREE, OR THAT DEFECTS HEREIN WILL BE CORRECTED.
--LICENSEE ASSUMES RESPONSIBILITY FOR SELECTION OF MATERIALS TO ACHIEVE ITS
--INTENDED RESULTS, AND FOR THE PROPER INSTALLATION, USE, AND RESULTS 
--OBTAINED THEREFROM.LICENSEE ASSUMES THE ENTIRE RISK OF THE FILE AND ITS 
--CONTENTS PROVING DEFECTIVE OR FAILING TO PERFORM PROPERLY AND IN SUCH 
--EVENT, LICENSEE SHALL ASSUME THE ENTIRE COST AND RISK OF ANY REPAIR, 
--SERVICE, CORRECTION, OR ANY OTHER LIABILITIES OR DAMAGES CAUSED BY OR 
--ASSOCIATED WITH THE SOFTWARE.IN NO EVENT SHALL LATTICE BE LIABLE TO ANY 
--PARTY FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, 
--INCLUDING LOST PROFITS, ARISING OUT OF THE USE OF THIS FILE OR ITS 
--CONTENTS, EVEN IF LATTICE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH 
--DAMAGES.LATTICE'S SOLE LIABILITY, AND LICENSEE'S SOLE REMEDY, IS SET FORTH 
--ABOVE.LATTICE DOES NOT WARRANT OR REPRESENT THAT THIS FILE, ITS CONTENTS 
--OR USE THEREOF DOES NOT INFRINGE ON THIRD PARTIES' INTELLECTUAL PROPERTY 
--RIGHTS, INCLUDING ANY PATENT. IT IS THE USER'S RESPONSIBILITY TO VERIFY THE 
--USER SOFTWARE DESIGN FOR CONSISTENCY AND FUNCTIONALITY THROUGH THE USE OF 
--FORMAL SOFTWARE VALIDATION METHODS.

--     ------------------------------------------------------------------

--VHDL instantiation template

component soc_golden_gsrd is
    port (ddr_ca_o: out std_logic_vector(5 downto 0);
        ddr_ck_o: out std_logic_vector(1 downto 0);
        ddr_cke_o: out std_logic_vector(0 downto 0);
        ddr_cs_o: out std_logic_vector(0 downto 0);
        ddr_dmi_io: inout std_logic_vector(3 downto 0);
        ddr_dq_io: inout std_logic_vector(31 downto 0);
        ddr_dqs_io: inout std_logic_vector(3 downto 0);
        rgmii_rxd_i: in std_logic_vector(3 downto 0);
        rgmii_txd_o: out std_logic_vector(3 downto 0);
        s0_gpio: inout std_logic_vector(7 downto 0);
        SPI_CLK: out std_logic;
        SPI_CSS: out std_logic;
        SPI_D2: inout std_logic;
        SPI_D3: inout std_logic;
        SPI_MISO: inout std_logic;
        SPI_MOSI: inout std_logic;
        clk_125_in: in std_logic;
        config_active_o: out std_logic;
        ddr_reset_n_o: out std_logic;
        init_done_o: out std_logic;
        irq_o: out std_logic;
        phy_resetn_o: out std_logic;
        pll_lock_o: out std_logic;
        pll_refclk_i: in std_logic;
        rgmii_mdc_o: out std_logic;
        rgmii_mdio_o: inout std_logic;
        rgmii_rxc_i: in std_logic;
        rgmii_rxctl_i: in std_logic;
        rgmii_txc_o: out std_logic;
        rgmii_txctl_o: out std_logic;
        rstn_i: in std_logic;
        s1_uart_rxd_i: in std_logic;
        s1_uart_txd_o: out std_logic;
        sclk_o: out std_logic;
        trn_err_o: out std_logic
    );
    
end component soc_golden_gsrd;
_inst: soc_golden_gsrd port map (config_active_o => __,
                                 ddr_ca_o => __,
                                 ddr_ck_o => __,
                                 ddr_cke_o => __,
                                 ddr_cs_o => __,
                                 ddr_dmi_io => __,
                                 ddr_dq_io => __,
                                 ddr_dqs_io => __,
                                 ddr_reset_n_o => __,
                                 irq_o => __,
                                 pll_refclk_i => __,
                                 sclk_o => __,
                                 phy_resetn_o => __,
                                 s0_gpio => __,
                                 clk_125_in => __,
                                 rgmii_txc_o => __,
                                 rgmii_mdc_o => __,
                                 rstn_i => __,
                                 SPI_CLK => __,
                                 SPI_D2 => __,
                                 SPI_D3 => __,
                                 SPI_MISO => __,
                                 SPI_MOSI => __,
                                 rgmii_rxd_i => __,
                                 rgmii_txd_o => __,
                                 rgmii_mdio_o => __,
                                 rgmii_rxc_i => __,
                                 rgmii_rxctl_i => __,
                                 rgmii_txctl_o => __,
                                 s1_uart_rxd_i => __,
                                 s1_uart_txd_o => __);
                                 