    tse_to_rgmii_bridge0 u_tse_to_rgmii_bridge0(.rst_n_i(rst_n_i),
        .plllock_i(plllock_i),
        .rgmii_rxc_i(rgmii_rxc_i),
        .rgmii_rxctl_i(rgmii_rxctl_i),
        .rgmii_rxd_i(rgmii_rxd_i),
        .rgmii_txc_i(rgmii_txc_i),
        .rgmii_txctl_o(rgmii_txctl_o),
        .rgmii_txd_o(rgmii_txd_o),
        .rxd_o(rxd_o),
        .rx_dv_o(rx_dv_o),
        .rx_er_o(rx_er_o),
        .txd_i(txd_i),
        .tx_en_i(tx_en_i),
        .tx_er_i(tx_er_i),
        .rgmii_mdio_o(rgmii_mdio_o),
        .tse_mdio_en_o(tse_mdio_en_o),
        .tse_mdo_o(tse_mdo_o),
        .tse_mdi_i_o(tse_mdi_i_o));
