/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2024.1.2406150513_p
    Soft IP Version: 1.0.0
    2024 08 25 04:37:07
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module tse_to_rgmii_bridge0 (rst_n_i, plllock_i, rgmii_rxc_i, rgmii_rxctl_i,
    rgmii_rxd_i, rgmii_txc_i, rgmii_txctl_o, rgmii_txd_o, rxd_o, rx_dv_o,
    rx_er_o, txd_i, tx_en_i, tx_er_i, rgmii_mdio_o, tse_mdio_en_o, tse_mdo_o,
    tse_mdi_i_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  rst_n_i;
    input  plllock_i;
    input  rgmii_rxc_i;
    input  rgmii_rxctl_i;
    input  [3:0]  rgmii_rxd_i;
    input  rgmii_txc_i;
    output  rgmii_txctl_o;
    output  [3:0]  rgmii_txd_o;
    output  [7:0]  rxd_o;
    output  rx_dv_o;
    output  rx_er_o;
    input  [7:0]  txd_i;
    input  tx_en_i;
    input  tx_er_i;
    inout  rgmii_mdio_o;
    input  tse_mdio_en_o;
    input  tse_mdo_o;
    output  tse_mdi_i_o;
endmodule