/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2024.1.2406150513_p
    Soft IP Version: 2.1.0
    2024 08 24 00:03:52
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module osc0 (en_i, clk_sel_i, clk_out_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  en_i;
    input  clk_sel_i;
    output  clk_out_o;
endmodule