define_compile_point  -comment {Automatically Inserted}  {v:work.axi4_interconnect0_ipgen_axi_cross_bar_Z11_layer0} -type {hard}
define_compile_point  -comment {Automatically Inserted}  {v:work.axi4_interconnect0_ipgen_lscc_sync_axi_interconnect_Z12_layer0} -type {hard}
define_compile_point  -comment {Automatically Inserted}  {v:work.axi4_interconnect1_ipgen_lscc_sync_axi_interconnect_Z116_layer0} -type {hard}
define_compile_point  -comment {Automatically Inserted}  {v:work.cpu0_1s_1s_0_1073741824_0_1073741824_0s_0_1s_0_143_layer0} -type {hard}
define_compile_point  -comment {Automatically Inserted}  {v:work.lpddr4_mc_contr0_ipgen_lpddr4_mc_sch_iface_top_Z161_layer0} -type {hard}
define_compile_point  -comment {Automatically Inserted}  {v:work.lpddr4_mc_contr0_ipgen_lpddr4_mc_prot_eng_Z172_layer0} -type {hard}
define_compile_point  -comment {Automatically Inserted}  {v:work.lpddr4_mc_contr0_ipgen_lscc_ddrphy_Z219_layer0} -type {hard}
define_compile_point  -comment {Automatically Inserted}  {v:work.lpddr4_mc_contr0} -type {hard}
define_compile_point  -comment {Automatically Inserted}  {v:work.mpmc0_ipgen_lscc_mpmc_axi_Z235_layer0} -type {hard}
define_compile_point  -comment {Automatically Inserted}  {v:work.qspi0_ipgen_qspi_flash_controller_core_Z266_layer0} -type {hard}
define_compile_point  -comment {Automatically Inserted}  {v:work.sgdma0_ipgen_sgdmac_core_Z281_layer0} -type {hard}
