#-- Lattice Semiconductor Corporation Ltd.
#-- Place & Route run script generated by Radiant

set ret 0
if {[catch {

sys_set_attribute -gui on -msg {C:/Users/SKothari/Downloads/GSRD2.0_Avant_CPNX_Beta/Final_Beta_Testing/golden_avant/soc_golden_gsrd/promote.xml}
msg_load {C:/Users/SKothari/Downloads/GSRD2.0_Avant_CPNX_Beta/Final_Beta_Testing/golden_avant/soc_golden_gsrd/promote.xml}
des_set_project_udb -in {soc_golden_gsrd_impl_1_map.udb} -out {soc_golden_gsrd_impl_1.udb} -milestone par -pm ap6a00b
des_set_reference_udb -clean
# par option
par_set_option { disable_timing_driven false placement_iterations 5 placement_iteration_start_point 1 placement_save_best_run "1"  number_of_host_machine_cores "8"  command_line_options "-exp nbrForceHoldTimeCorrection=1" stop_once_timing_is_met true  set_speed_grade_for_setup_optimization "1" set_speed_grade_for_hold_optimization m disable_auto_hold_timing_correction false prioritize_hold_correction_over_setup_performance true run_placement_only false impose_hold_timing_correction false}
# run place & route
par_run
# backup netlist & constraint file
if {[file exists {C:/Users/SKothari/Downloads/GSRD2.0_Avant_CPNX_Beta/Final_Beta_Testing/golden_avant/soc_golden_gsrd/impl_1/soc_golden_gsrd_impl_1_syn.udb}] && [file exists {C:/Users/SKothari/Downloads/GSRD2.0_Avant_CPNX_Beta/Final_Beta_Testing/golden_avant/soc_golden_gsrd/impl_1/soc_golden_gsrd_impl_1_map.udb}] && [file exists {C:/Users/SKothari/Downloads/GSRD2.0_Avant_CPNX_Beta/Final_Beta_Testing/golden_avant/soc_golden_gsrd/impl_1/soc_golden_gsrd_impl_1.udb}]} {
  file delete -force {C:/Users/SKothari/Downloads/GSRD2.0_Avant_CPNX_Beta/Final_Beta_Testing/golden_avant/soc_golden_gsrd/impl_1/incr/soc_golden_gsrd_impl_1_syn.udb} {C:/Users/SKothari/Downloads/GSRD2.0_Avant_CPNX_Beta/Final_Beta_Testing/golden_avant/soc_golden_gsrd/impl_1/incr/soc_golden_gsrd_impl_1_map.udb} {C:/Users/SKothari/Downloads/GSRD2.0_Avant_CPNX_Beta/Final_Beta_Testing/golden_avant/soc_golden_gsrd/impl_1/incr/soc_golden_gsrd_impl_1.udb} {C:/Users/SKothari/Downloads/GSRD2.0_Avant_CPNX_Beta/Final_Beta_Testing/golden_avant/soc_golden_gsrd/impl_1/incr/lastrun.pdc}
  file copy -force -- {C:/Users/SKothari/Downloads/GSRD2.0_Avant_CPNX_Beta/Final_Beta_Testing/golden_avant/soc_golden_gsrd/impl_1/soc_golden_gsrd_impl_1_syn.udb} {C:/Users/SKothari/Downloads/GSRD2.0_Avant_CPNX_Beta/Final_Beta_Testing/golden_avant/soc_golden_gsrd/impl_1/incr/postsyn.udb}
  file copy -force -- {C:/Users/SKothari/Downloads/GSRD2.0_Avant_CPNX_Beta/Final_Beta_Testing/golden_avant/soc_golden_gsrd/impl_1/soc_golden_gsrd_impl_1_map.udb} {C:/Users/SKothari/Downloads/GSRD2.0_Avant_CPNX_Beta/Final_Beta_Testing/golden_avant/soc_golden_gsrd/impl_1/incr/postmap.udb}
  file copy -force -- {C:/Users/SKothari/Downloads/GSRD2.0_Avant_CPNX_Beta/Final_Beta_Testing/golden_avant/soc_golden_gsrd/impl_1/soc_golden_gsrd_impl_1.udb} {C:/Users/SKothari/Downloads/GSRD2.0_Avant_CPNX_Beta/Final_Beta_Testing/golden_avant/soc_golden_gsrd/impl_1/incr/postpar.udb}
  if [file exists {C:/Users/SKothari/Downloads/GSRD2.0_Avant_CPNX_Beta/Final_Beta_Testing/golden_avant/soc_golden_gsrd/source/impl_1/soc_board_constraints.pdc}] {
    file copy -force -- {C:/Users/SKothari/Downloads/GSRD2.0_Avant_CPNX_Beta/Final_Beta_Testing/golden_avant/soc_golden_gsrd/source/impl_1/soc_board_constraints.pdc} {C:/Users/SKothari/Downloads/GSRD2.0_Avant_CPNX_Beta/Final_Beta_Testing/golden_avant/soc_golden_gsrd/impl_1/incr/lastrun.pdc}
  }
}

} out]} {
   puts $out
   set ret 1
}

exit -force ${ret}
