#-- Lattice Semiconductor Corporation Ltd.
#-- Bitgen run script generated by Radiant

set ret 0
if {[catch {

sys_set_attribute -gui on -msg {C:/Users/SKothari/Downloads/GSRD2.0_Avant_CPNX_Beta/Final_Beta_Testing/golden_avant/soc_golden_gsrd/promote.xml}
msg_load {C:/Users/SKothari/Downloads/GSRD2.0_Avant_CPNX_Beta/Final_Beta_Testing/golden_avant/soc_golden_gsrd/promote.xml}
des_set_project_udb -in {soc_golden_gsrd_impl_1.udb} -milestone bit -pm ap6a00b
# bitgen option
bit_set_option { enable_early_io_wakeup false output_format "binary"   ip_evaluation false register_initialization true bitstream_mode normal }
#-- write result file
bit_generate -w {C:/Users/SKothari/Downloads/GSRD2.0_Avant_CPNX_Beta/Final_Beta_Testing/golden_avant/soc_golden_gsrd/impl_1/soc_golden_gsrd_impl_1}

} out]} {
   puts $out
   set ret 1
}

exit -force ${ret}
