#-- Lattice Semiconductor Corporation Ltd.
#-- Map run script generated by Radiant

set ret 0
if {[catch {

sys_set_attribute -gui on -msg {C:/Users/SKothari/Downloads/GSRD2.0_Avant_CPNX_Beta/Final_Beta_Testing/golden_avant/soc_golden_gsrd/promote.xml}
msg_load {C:/Users/SKothari/Downloads/GSRD2.0_Avant_CPNX_Beta/Final_Beta_Testing/golden_avant/soc_golden_gsrd/promote.xml}
des_set_project_udb -in {soc_golden_gsrd_impl_1_syn.udb} -out {soc_golden_gsrd_impl_1_map.udb} -milestone map -pm ap6a00b
des_set_reference_udb -clean
map_set_option {pdc_file "C:/Users/SKothari/Downloads/GSRD2.0_Avant_CPNX_Beta/Final_Beta_Testing/golden_avant/soc_golden_gsrd/source/impl_1/soc_board_constraints.pdc"}
# map option
map_set_option { report_symbol_cross_reference false report_signal_cross_reference false infer_gsr false ignore_constraint_errors false }
map_run

} out]} {
   puts $out
   set ret 1
}
exit -force ${ret}
