/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2024.1.2406150513_p
    Soft IP Version: 1.6.0
    2024 08 24 00:41:05
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module tse_mac0 (int_o, ignore_pkt_i, reset_n_i, mdo_o, rx_error_o,
    apb_pready_o, axis_rx_tvalid_o, rx_fifo_error_o, rx_dv_i, axis_rx_tready_i,
    tx_discfrm_o, tx_sndpausreq_i, tx_er_o, rx_stat_vector_o, rxd_i,
    apb_pslverr_o, clk_i, rxmac_clk_i, txmac_clk_i, apb_paddr_i, apb_prdata_o,
    rx_eof_o, tx_sndpaustim_i, tx_staten_o, rx_staten_o, cpu_if_gbit_en_o,
    tx_macread_o, mdc_i, mdi_i, rx_er_i, axis_rx_tdata_o, tx_fifoctrl_i,
    tx_en_o, axis_rx_tlast_o, axis_rx_tkeep_o, apb_pwdata_i, axis_tx_tdata_i,
    axis_tx_tready_o, apb_pwrite_i, apb_psel_i, apb_penable_i, tx_statvec_o,
    mdio_en_o, axis_tx_tvalid_i, axis_tx_tlast_i, axis_tx_tkeep_i, txd_o,
    tx_done_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    output  int_o;
    input  ignore_pkt_i;
    input  reset_n_i;
    output  mdo_o;
    output  rx_error_o;
    output  apb_pready_o;
    output  axis_rx_tvalid_o;
    output  rx_fifo_error_o;
    input  rx_dv_i;
    input  axis_rx_tready_i;
    output  tx_discfrm_o;
    input  tx_sndpausreq_i;
    output  tx_er_o;
    output  [31:0]  rx_stat_vector_o;
    input  [7:0]  rxd_i;
    output  apb_pslverr_o;
    input  clk_i;
    input  rxmac_clk_i;
    input  txmac_clk_i;
    input  [10:0]  apb_paddr_i;
    output  [31:0]  apb_prdata_o;
    output  rx_eof_o;
    input  [15:0]  tx_sndpaustim_i;
    output  tx_staten_o;
    output  rx_staten_o;
    output  cpu_if_gbit_en_o;
    output  tx_macread_o;
    input  mdc_i;
    input  mdi_i;
    input  rx_er_i;
    output  [7:0]  axis_rx_tdata_o;
    input  tx_fifoctrl_i;
    output  tx_en_o;
    output  axis_rx_tlast_o;
    output  axis_rx_tkeep_o;
    input  [31:0]  apb_pwdata_i;
    input  [7:0]  axis_tx_tdata_i;
    output  axis_tx_tready_o;
    input  apb_pwrite_i;
    input  apb_psel_i;
    input  apb_penable_i;
    output  [31:0]  tx_statvec_o;
    output  mdio_en_o;
    input  axis_tx_tvalid_i;
    input  axis_tx_tlast_i;
    input  axis_tx_tkeep_i;
    output  [7:0]  txd_o;
    output  tx_done_o;
endmodule